name: filearch
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - click=8.2.0
  - colorama=0.4.6
  - intel-openmp=2024.2.1
  - joblib=1.5.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libsqlite=3.49.2
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - libzlib=1.3.1
  - mkl=2024.2.2
  - nltk=3.9.1
  - numpy=1.24.2
  - openssl=3.5.0
  - pandas=1.5.3
  - pip=25.1.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytz=2025.2
  - regex=2024.11.6
  - scikit-learn=1.2.2
  - scipy=1.15.2
  - setuptools=80.1.0
  - six=1.17.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tqdm=4.67.1
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.45.1
  - pip:
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - filelock==3.18.0
      - fsspec==2025.3.2
      - huggingface-hub==0.31.2
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - packaging==25.0
      - pillow==11.2.1
      - python-pptx==1.0.2
      - pyyaml==6.0.2
      - rarfile==4.2
      - requests==2.32.3
      - safetensors==0.5.3
      - sentence-transformers==4.1.0
      - sentencepiece==0.2.0
      - sympy==1.14.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - torchvision==0.22.0
      - transformers==4.51.3
      - typing-extensions==4.13.2
      - urllib3==2.4.0
      - xlsxwriter==3.2.3
